mod commands;
pub mod db;
mod models;

use log::info;
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Build the specta command registry
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::get_prompts,
        commands::save_prompt,
        commands::delete_prompt,
        commands::duplicate_prompt,
        commands::get_snippets,
        commands::save_snippet,
        commands::delete_snippet,
        commands::get_views,
        commands::get_view_by_id,
        commands::save_view,
        commands::delete_view,
        commands::get_all_tags,
        commands::get_table_names,
        commands::get_table_info,
        commands::get_table_rows,
        commands::clear_table,
        commands::export_database_as_json,
        commands::get_database_path,
    ]);

    // Export TypeScript bindings in debug builds
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// This file is auto-generated by Specta. Do not edit.\n// @ts-nocheck\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            // Initialize database
            let handle = app.handle().clone();
            tauri::async_runtime::block_on(async move {
                match db::init_db(&handle).await {
                    Ok(pool) => {
                        info!("Database initialized successfully");
                        handle.manage(pool);
                    }
                    Err(e) => {
                        log::error!("Failed to initialize database: {}", e);
                        panic!("Database initialization failed: {}", e);
                    }
                }
            });
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
