// This file is auto-generated by Specta. Do not edit.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get all prompts with their tags and template values
 */
async getPrompts(filter: FilterConfig | null, sort: SortConfig | null) : Promise<Result<Prompt[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompts", { filter, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a prompt (upsert)
 */
async savePrompt(prompt: PromptInput) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a prompt
 */
async deletePrompt(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Duplicate a prompt
 */
async duplicatePrompt(id: string) : Promise<Result<Prompt | null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all snippets with their tags
 */
async getSnippets() : Promise<Result<Snippet[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a snippet (upsert)
 */
async saveSnippet(snippet: SnippetInput) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { snippet }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a snippet
 */
async deleteSnippet(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all views
 */
async getViews() : Promise<Result<View[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_views") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a view by ID
 */
async getViewById(id: string) : Promise<Result<View | null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_view_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a view (upsert)
 */
async saveView(view: ViewInput) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_view", { view }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a view
 */
async deleteView(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_view", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all tag names
 */
async getAllTags() : Promise<Result<string[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all table names (for debugging)
 */
async getTableNames() : Promise<Result<string[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get table schema information
 */
async getTableInfo(tableName: string) : Promise<Result<TableColumn[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_info", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all rows from a table (for debugging)
 */
async getTableRows(tableName: string) : Promise<Result<TableRow[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_rows", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all rows from a table (for debugging)
 */
async clearTable(tableName: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_table", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export entire database as JSON (for debugging)
 */
async exportDatabaseAsJson() : Promise<Result<ExportedDatabase, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_database_as_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the database file path
 */
async getDatabasePath() : Promise<Result<string, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type DbError = { Database: string } | { NotFound: string } | { Serialization: string }
export type ExportedDatabase = { tables: Partial<{ [key in string]: ExportedTable }> }
export type ExportedTable = { schema: TableColumn[]; rows: TableRow[] }
export type FilterConfig = { tags?: string[] | null; search?: string | null; favorite?: boolean | null }
/**
 * Prompt with tags and template values - returned to frontend
 */
export type Prompt = { id: string; createdAt: number | null; title: string | null; text: string; description: string | null; mode: string; tags: string[]; templateValues?: Partial<{ [key in string]: string }> | null }
/**
 * Input for saving a prompt
 */
export type PromptInput = { id: string; createdAt: number | null; title: string | null; text: string; description: string | null; mode: string; tags: string[]; templateValues?: Partial<{ [key in string]: string }> | null }
/**
 * Snippet with tags - returned to frontend
 */
export type Snippet = { id: string; createdAt: number | null; value: string; description: string | null; tags: string[] }
/**
 * Input for saving a snippet
 */
export type SnippetInput = { id: string; createdAt: number | null; value: string; description: string | null; tags: string[] }
export type SortConfig = { by: string; order: string }
export type TableColumn = { cid: number; name: string; type: string; notnull: number; dfltValue?: string | null; pk: number }
export type TableRow = (Partial<{ [key in string]: string }>)
/**
 * View - returned to frontend
 */
export type View = { id: string; name: string; type: string; config: ViewConfig; createdAt: number }
/**
 * View configuration for filtering and sorting
 */
export type ViewConfig = { filter?: FilterConfig | null; sort?: SortConfig | null }
/**
 * Input for saving a view
 */
export type ViewInput = { id: string; name: string; type: string; config: ViewConfig; createdAt: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
