// This file is auto-generated by Specta. Do not edit.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get all prompts with their tags from cache
 */
async getPrompts(filter: FilterConfig | null, sort: SortConfig | null) : Promise<Result<Prompt[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompts", { filter, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a prompt to cache (upsert)
 * STRICT VAULT-FIRST:
 * 1. Check if vault is configured
 * 2. Write to filesystem (Master)
 * 3. Update database (Cache)
 */
async savePrompt(prompt: PromptInput) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a prompt from cache
 * STRICT VAULT-FIRST:
 * 1. Check if vault is configured
 * 2. Delete from filesystem (Master)
 * 3. Delete from database (Cache)
 */
async deletePrompt(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Duplicate a prompt
 * STRICT VAULT-FIRST:
 * 1. Check if vault is configured
 * 2. Write new file to filesystem (Master)
 * 3. Update database (Cache)
 */
async duplicatePrompt(id: string) : Promise<Result<Prompt | null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all views
 */
async getViews() : Promise<Result<View[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_views") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a view by ID
 */
async getViewById(id: string) : Promise<Result<View | null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_view_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a view (upsert)
 */
async saveView(view: ViewInput) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_view", { view }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a view
 */
async deleteView(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_view", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all tag names
 */
async getAllTags() : Promise<Result<string[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all table names (for debugging)
 */
async getTableNames() : Promise<Result<string[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get table schema information
 */
async getTableInfo(tableName: string) : Promise<Result<TableColumn[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_info", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all rows from a table (for debugging)
 */
async getTableRows(tableName: string) : Promise<Result<TableRow[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_rows", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all rows from a table (for debugging)
 */
async clearTable(tableName: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_table", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export entire database as JSON (for debugging)
 */
async exportDatabaseAsJson() : Promise<Result<ExportedDatabase, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_database_as_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the database file path
 */
async getDatabasePath() : Promise<Result<string, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get application configuration
 */
async getConfig() : Promise<Result<AppConfig, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save application configuration
 */
async saveConfig(config: AppConfig) : Promise<Result<null, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan vault and return all prompt files
 */
async scanVault() : Promise<Result<PromptFile[], VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a single prompt file by ID
 */
async readPromptFile(id: string) : Promise<Result<PromptFile, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_prompt_file", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a prompt file
 */
async writePromptFile(prompt: PromptFile) : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_prompt_file", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a prompt file
 */
async deletePromptFile(id: string) : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt_file", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync vault files to database cache
 * STRICT VAULT-FIRST:
 * 1. Scan filesystem
 * 2. Upsert all found files to DB
 * 3. Remove DB entries that are not in the scan
 */
async syncVault() : Promise<Result<SyncStats, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching the vault for external changes
 */
async startVaultWatch() : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_vault_watch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application configuration stored in TOML format
 */
export type AppConfig = { 
/**
 * Path to the vault directory containing prompt markdown files (as string for TypeScript)
 */
vaultPath: string | null; 
/**
 * UI theme name
 */
theme?: string; 
/**
 * View preferences
 */
view?: ViewSettings; 
/**
 * Frontmatter preferences
 */
frontmatter?: FrontmatterSettings }
/**
 * Configuration errors
 */
export type ConfigError = { PathError: string } | { IoError: string } | { ParseError: string } | { SerializeError: string }
export type DbError = { Database: string } | { NotFound: string } | { Serialization: string }
export type ExportedDatabase = { tables: Partial<{ [key in string]: ExportedTable }> }
export type ExportedTable = { schema: TableColumn[]; rows: TableRow[] }
export type FilterConfig = { tags?: string[] | null; search?: string | null; favorite?: boolean | null }
export type FrontmatterSettings = { promptTagsProperty?: string; addPromptsTagToTags?: boolean }
/**
 * Prompt with tags - returned to frontend (legacy, for cache-based queries)
 */
export type Prompt = { id: string; created: string | null; text: string; tags: string[]; filePath: string | null; title: string | null }
/**
 * A prompt file representation (parsed from markdown)
 */
export type PromptFile = { 
/**
 * File identifier (relative file path)
 */
id: string; 
/**
 * File path relative to vault root
 */
filePath: string; 
/**
 * Tags from frontmatter
 */
tags: string[]; 
/**
 * Created timestamp from frontmatter (ISO string)
 */
created: string | null; 
/**
 * The prompt content (from code block)
 */
content: string; 
/**
 * Hash of the full file contents
 */
fileHash?: string | null; 
/**
 * Optional prompt title from frontmatter
 */
title: string | null }
/**
 * Input for saving a prompt (legacy, for cache-based operations)
 */
export type PromptInput = { id: string; created: string | null; text: string; tags: string[]; filePath: string | null; previousFilePath: string | null; title: string | null }
export type SortConfig = { by: string; order: string }
export type SyncStats = { found: number; updated: number; deleted: number }
export type TableColumn = { cid: number; name: string; type: string; notnull: number; dfltValue?: string | null; pk: number }
export type TableRow = (Partial<{ [key in string]: string }>)
/**
 * Vault operation errors
 */
export type VaultError = "NotConfigured" | { NotFound: string } | { PathNotFound: string } | { IoError: string } | { ParseError: string } | { SerializeError: string } | { InvalidFilename: string } | { InvalidFilePath: string } | { FileAlreadyExists: string } | { InvalidContent: string }
/**
 * View - returned to frontend
 */
export type View = { id: string; name: string; type: string; config: ViewConfig; created: string }
/**
 * View configuration for filtering and sorting
 */
export type ViewConfig = { filter?: FilterConfig | null; sort?: SortConfig | null }
/**
 * Input for saving a view
 */
export type ViewInput = { id: string; name: string; type: string; config: ViewConfig; created: string }
export type ViewSettings = { showPromptTitles?: boolean; showFullPrompt?: boolean; showPromptTags?: boolean; showCreatedDate?: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
